Module 4
malicuss/Task_SimpleWebApp pull request #7
Opened 2022-11-28 09:47 UTC by malicuss

2022-12-05 19:55 UTC, Ungerfall requested changes
Move WebApi to separate project. Your core should have two composition roots:
1.  WebApp
2.  WebApi

Do not put refactoring in PR. Do it in master.

2022-12-05 19:55 UTC, Ungerfall commented on SimpleWebApp/Controllers/ApiController.cs
> +public class ApiController : ControllerBase
Controller per resource. If you want api prefix better to configure routing

2022-12-05 19:55 UTC, Ungerfall commented on SimpleWebApp/Controllers/ApiController.cs
> +    public async Task<ActionResult<Category>> GetCategory([FromQuery]int categoryId)
Don't need to explicitly name GetCategory since you are using `GET` verb

2022-12-05 19:55 UTC, Ungerfall commented on SimpleWebApp/Controllers/ApiController.cs
> +    public async Task<bool> CreateProduct([FromForm]Product p)
Don't need to explicitly name CreateCategory since you are using `POST` verb

2022-12-05 19:55 UTC, Ungerfall commented on SimpleWebApp/Controllers/ApiController.cs
> +    public async Task<bool> DeleteProduct([FromForm]Product p)
Explicit Delete, but `DELETE` verb is used

2022-12-05 19:55 UTC, Ungerfall commented on SimpleWebApp/Controllers/ApiController.cs
> +    public async Task<bool> UpdateProduct([FromForm]Product p)
For update use `PATCH` or `PUT`

2022-12-06 10:23 UTC, malicuss commented
Changed structure to resolve comments.

2022-12-06 11:17 UTC, Ungerfall approved these changes

2022-12-06 11:20 UTC, merged